name: 'vmtest-action'
description: 'Programmatically run tests in a virtualized machine'
author: 'danobi'
inputs: 
  name:
    description: 'Name for vmtest target.'
    default: 'vmtest-action target'
    required: false
  image:
    description: 'Path to virtual machine image. Optional field, but one of `image` or `kernel` must be specified.'
    default: ''
    required: false
  image_url:
    description: 'URL to virtual machine image. Optional field, but one of `image` or `kernel` must be specified. `image` may not be specified if `image_url` is provided.
    default: ''
    required: false
  uefi:
    description: 'Whether to use UEFI boot or not'
    default: 'false'
    required: false
  kernel:
    description: 'Path to kernel. Typically named `vmlinuz` or `bzImage`. Optional field, but one of `image` and `kernel` must be specified.'
    default: ''
    required: false
  kernel_url:
    description: 'URL to kernel. Optional field, but one of `image` or `kernel` must be specified. `kernel` may not be specified if `kernel_url` is provided.
    default: ''
    required: false
  kernel_args:
    description: 'Additional kernel command line arguments to append to vmtest generated kernel arguments. `kernel` must be specified for this field to be effective.'
    default: ''
    required: false
  command:
    description: 'Command to run inside VM. The specified command must be an absolute path. Note that the specified command is not run inside a shell by default. If you want a shell, use /bin/bash -c "$SHELL_CMD_HERE".'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
